---
title: "Kortrapport - eksempler"
author: "DHJ"
date: "27 4 2022"
params:
  paramgroup: Metals and metalloids
output: 
  bookdown::html_document2: default  
    
---

* Basert på 'Mal_for_kortrapport'  


```{r, echo=FALSE}

knitr::opts_chunk$set(echo = FALSE)  

```


```{r packages, results='hide', message=FALSE, warning=FALSE}

library(dplyr)
library(tidyr)
library(ggplot2)
library(lubridate)
library(flextable)
library(glue)
library(readxl)
library(purrr)
library(leftcensored)   # DHJ's package (https://github.com/DagHjermann/leftcensored)

library(safejoin) # https://github.com/moodymudskipper/safejoin

# source("01_Get_chemical_data_NIVAbasen_functions.R")  # for get_standard_parametername()

```

```{r selected_year}

selected_year <- 2020

```


## Report contents        

This report is based on Milkys data through **`r selected_year`**.     

```{r read_data}

#
# Raw data
#
fn <- "Files_from_Jupyterhub_2020/Raw_data/109_adjusted_data_2021-09-15.rds"                         # data FROM Milkys2 on PC 
dat_all <- readRDS(fn)

#
# Parameter groups
#
lookup_paramgroup <- read_excel("Input_files_2020/Lookup table - substance groups.xlsx")
lookup_stations <- read_excel("Files_from_Jupyterhub_2020/Lookup for big excel - stations.xlsx")

dat_1 <- dat_all %>%
  left_join(lookup_paramgroup %>% select(PARAM, Substance.Group)) %>%
  filter(Substance.Group %in% params$paramgroup) %>%
  add_count(PARAM) %>%
  filter(n >= 100) %>%
  left_join(lookup_stations %>% select(STATION_CODE, Station.Name)) %>%
  mutate(Station = paste(STATION_CODE, Station.Name))

param_values <- unique(dat_1$PARAM)
  
#
# Big excel file
#
# datxl <- readr::read_csv("Files_from_Jupyterhub_2020/Big_excel_table/Data_xl_2021-10-08_ver04.csv")
datxl <- readRDS("Files_from_Jupyterhub_2020/Big_excel_table/Data_xl_2021-09-15_ver03.rds") %>%
  filter(PARAM %in% param_values)
  
table(dat_1$PARAM)
table(datxl$PARAM)  

```

```{r lookup_eqs_ww}

lookup_eqs_ww <- datxl %>%
  filter(
    !is.na(EQS),
    Basis %in% "WW"
    ) %>%
  distinct(PARAM, LATIN_NAME, TISSUE_NAME, EQS) %>%
  mutate(TISSUE_NAME = case_when(
    TISSUE_NAME == "Muscle" ~ "Muskel",
    TISSUE_NAME == "Liver" ~ "Lever",
    TRUE ~ TISSUE_NAME)
    ) %>%
  rename(EQS_WW = EQS)

check <- lookup_eqs_ww %>% 
  add_count(PARAM, LATIN_NAME, TISSUE_NAME) %>%
  filter(n > 1)

if (nrow(check) > 0){
  stop("More than one EQS per parameter!")
}

dat_2 <- dat_1 %>%
  left_join(lookup_eqs_ww, by = c("PARAM", "LATIN_NAME", "TISSUE_NAME")) %>%
  mutate(
    Above_EQS = case_when(
      VALUE_WW > EQS_WW ~ "Over",
      VALUE_WW <= EQS_WW ~ "Under",
      TRUE ~ as.character(NA))
  ) 


```


```{r calc_medians}  

dat_medium <- dat_2 %>%
  group_by(Station) %>%
  mutate(n_after_2018 = sum(MYEAR >= 2018)) %>%
  filter(
    n_after_2018 > 0) %>%
  group_by(PARAM, LATIN_NAME, TISSUE_NAME, Station, MYEAR) %>%
  summarize(
    VALUE_WW_med = median(VALUE_WW, na.rm = TRUE),
    N = n(),
    N_underLOQ = sum(FLAG1 %in% "<"),
    Prop_underLOQ = N_underLOQ/N,
    FLAG1 = case_when(
      Prop_underLOQ < 0.5 ~ as.character(NA),
      Prop_underLOQ >= 0.5 ~ "<"),
    .groups = "drop") %>%
  left_join(lookup_eqs_ww, by = c("PARAM", "LATIN_NAME", "TISSUE_NAME")) %>%
  mutate(
    Above_EQS = case_when(
      VALUE_WW_med > EQS_WW ~ "Over",
      VALUE_WW_med <= EQS_WW ~ "Under",
      TRUE ~ as.character(NA))
  )

?leftcensored_lm
```



```{r trend_ww_1}

#
# Linear trend
# Full time series  
#


# Test 

if (FALSE){
  # debugonce(get_trend)
  get_trend("HG", "Mytilus edulis", "Whole soft body", "51A Byrkjenes", data = dat_medium)
  get_trend("HG", "Mytilus edulis", "Whole soft body", "51A Byrkjenes", data = dat_2, y = "VALUE_WW")
  milkys_select_rows("HG", "Mytilus edulis", "Whole soft body", "51A Byrkjenes", data = dat_medium)
  
  get_trend("HG", "Mytilus edulis", "Whole soft body", "51A Byrkjenes", data = dat_medium, firstyear = 2011)
  get_trend("HG", "Gadus morhua", "Muskel", "02B Kirkøy (north)", data = dat_medium)
  
  get_trend("HG", "Mytilus edulis", "Whole soft body", "51A Byrkjenes", data = dat_medium)
  
}

?leftcensored_prepare

xtabs(~PARAM + addNA(FLAG1), dat_medium %>% filter(LATIN_NAME == "Mytilus edulis"))

test1 <- milkys_select_rows("AG", "Mytilus edulis", data = dat_medium)
xtabs(~Station + addNA(FLAG1), test1)
ggplot(test1, aes(MYEAR, VALUE_WW_med, color = FLAG1)) + 
  geom_point() + 
  facet_wrap("Station") +
  scale_y_log10()

test2 <- leftcensored_prepare(test1, var_year = "MYEAR", var_concentration = VALUE_WW_med)

```

```{r trend_ww_2}

# Get all regression estimates as list

get_all_trends <- function(series, firstyear = NULL, data){
  
  trend_coef_list <- list(
    param = series$PARAM,
    species = series$LATIN_NAME,
    tissue = series$TISSUE_NAME,
    station = series$Station) %>% purrr::pmap(get_trend, firstyear = firstyear, data = data)
  
  # Find those that failed  
  failed <- trend_coef_list %>% map_lgl(~is.null(.))
  mean(failed)
  
  # Put togethr to a data frame  
  trend_coef <- trend_coef_list[!failed] %>% 
    bind_rows() %>%
    mutate(CI_lo = Est - 2*SE, 
           CI_up = Est + 2*SE,
           Trend = case_when(
             CI_lo > 0 ~ "Up",
             CI_up < 0 ~ "Down",
             TRUE ~ "Inconclusive")
    )
  
  trend_coef
  
}


```


```{r trend_ww_3}

trend_series <- dat_medium %>%
  filter(!is.na(VALUE_WW_med)) %>%
  count(PARAM, LATIN_NAME, TISSUE_NAME, Station) %>%
  filter(n >= 3)

trend_coef_long <- get_all_trends(series = trend_series, data = dat_medium)
trend_coef_10yr <- get_all_trends(series = trend_series, data = dat_medium, firstyear = 2011)


```



## HG  
```{r}

param <- "HG"
species <- "Mytilus edulis" 
tissue <- "Whole soft body" 

param <- "HG"
species <- "Gadus morhua" 
tissue <- "Muskel" 


datxl_sel <- datxl %>%
  filter(
    PARAM %in% param, 
    LATIN_NAME %in% species,
    TISSUE_NAME %in% tissue)

dat_sel <- dat_2 %>%
  filter(
    PARAM %in% param, 
    LATIN_NAME %in% species)  

dat_sel_medium <- dat_medium %>%
  filter(
    PARAM %in% param, 
    LATIN_NAME %in% species)

station_order <- c(
  "19B NA", "10B Varangerfjord", "45B2 Hammerfest (havn)", "43B2 Tromsø harbour",
  "98B1 Lofoten, Skrova", "96B Helgelandskysten area by Sandnessjøen", 
   "80B Munkholmen", "13B Kristiansand harbour", "28B Ålesund area by Hundsvær",
  "24B Bergen havn", "23B Bømlo north", "53B Inner Sørfjord", 
  "15B Farsund area", "71B Grenlandsfjorden Breviks area", 
  "36B Færder area", "30B Inner Oslofjord", "02B Kirkøy (north)")
 
dat_sel_medium$Station <- factor(dat_sel_medium$Station, levels = rev(station_order))


```




### Overview plot    
```{r, fig.width=11, fig.height=7}

yrs <- 2005:2021
  
ggplot(dat_sel_medium %>% filter(MYEAR %in% yrs), aes(MYEAR, Station, fill = VALUE_WW_med)) +
  geom_tile() +
  geom_tile(data = dat_sel_medium %>% filter(MYEAR %in% yrs, Above_EQS %in% "Over"),
            color = "red", size = 1.5) +
  geom_text(aes(label = round(VALUE_WW_med, 3)), size = 3) +
  scale_fill_viridis_c(trans = "log10", breaks = c(0.1,1,10,100)) +
  scale_color_manual(values = c("red", "white")) +
  scale_alpha_manual(values = c(1, 0)) +
  scale_x_continuous(breaks = seq(2005, 2020, 2))

# unique(dat_sel_medium$Station) %>% dput()


```



```{r}

trend_coef_long_sel <- trend_coef_long %>%
  filter(
    PARAM %in% param, 
    LATIN_NAME %in% species)

trend_coef_10yr_sel <- trend_coef_10yr %>%
  filter(
    PARAM %in% param, 
    LATIN_NAME %in% species)

trend_coef_long_sel$Station <- factor(trend_coef_long_sel$Station, levels = rev(station_order))
trend_coef_10yr_sel$Station <- factor(trend_coef_10yr_sel$Station, levels = rev(station_order))

ggplot(trend_coef_long_sel, aes(x = Station)) +
  geom_pointrange(aes(y = Est, ymin = CI_lo, ymax = CI_up, color = Trend)) +
  scale_color_manual(values = c("green2", "grey20", "red2")) +
  coord_flip(ylim = range(trend_coef_long_sel$Est))

ggplot(trend_coef_10yr_sel, aes(x = Station)) +
  geom_pointrange(aes(y = Est, ymin = CI_lo, ymax = CI_up, color = Trend)) +
  scale_color_manual(values = c("green2", "grey20", "red2")) +
  coord_flip(ylim = range(trend_coef_10yr_sel$Est))

```
### Combine  
```{r, fig.width=13, fig.height=9}

yrs <- 2004:2020

dat_sel_medium_plot <- dat_sel_medium %>%
  mutate(Station2 = substr(Station, 1, 15),
         Station2 = factor(Station2, levels = rev(substr(station_order, 1, 15))))

gg1 <- ggplot(dat_sel_medium_plot %>% filter(MYEAR %in% yrs), 
              aes(MYEAR, Station2, fill = VALUE_WW_med)) +
  geom_tile() +
  geom_tile(data = dat_sel_medium_plot %>% filter(MYEAR %in% yrs, 
                                             Above_EQS %in% "Over"),
            color = "red", size = 1.5) +
  geom_text(aes(label = round(VALUE_WW_med, 3)), size = 3) +
  scale_fill_viridis_c(trans = "log10", breaks = c(0.1,1,10,100)) +
  scale_color_manual(values = c("red", "white")) +
  scale_alpha_manual(values = c(1, 0)) +
  scale_x_continuous(breaks = seq(2004, 2020, 2)) +
  theme(legend.position = "none")

gg_list <- list(trend_coef_long_sel, trend_coef_10yr_sel) %>%
  map(
    ~ggplot(., aes(x = Station)) +
      geom_pointrange(aes(y = Est, ymin = CI_lo, ymax = CI_up, color = Trend)) +
      scale_color_manual(values = c("green2", "grey20", "red2")) +
      geom_hline(yintercept = 0) +
      coord_flip(ylim = range(.$Est)) +
      theme_bw())

gg_list[[1]] <- gg_list[[1]] 
  

# Test
# cowplot::plot_grid(gg1, 
#                    gg2, 
#                    nrow = 1)

cowplot::plot_grid(gg1, 
                   gg_list[[1]] + 
                     theme(axis.title.y = element_blank(),
                           axis.text.y = element_blank(),
                           legend.position = "none"), 
                   gg_list[[2]] + 
                     theme(axis.title.y = element_blank(),
                           axis.text.y = element_blank()), 
                   rel_widths = c(2.8, 0.6, 1),
                   nrow = 1)

# tidstrend punkter: pil/trekant opp/ned avhengig av retning
# < som ekstra tegn over konsentrasjon
# farger i hht, proref
# følg grense på 5 år for trender  
#  
# For siste år: boksplott (med proref lagt på som linjer)  
#
# "Stor excel" også - trenger ikke være formatert
# 

```
