---
title: Cross-referencing figures, tables, and equations
author: Generated by bookdown
output:
  bookdown::html_document2: default
  bookdown::pdf_document2: default
---

```{r packages, echo=FALSE, results='hide', message=FALSE, warning=FALSE}
library(dplyr)
library(flextable)

```

See Figure \@ref(fig:cars-plot).

```{r cars-plot, fig.cap="The cars data.", echo=FALSE}
par(mar = c(4, 4, .2, .1))
plot(cars)  # a scatterplot
```

Also see Equation \@ref(eq:mean).

\begin{equation}
\bar{X} = \frac{\sum_{i=1}^n X_i}{n} (\#eq:mean)
\end{equation}

And see Table \@ref(tab:mtcars).

```{r mtcars, echo=FALSE}
knitr::kable(mtcars[1:5, 1:5], caption = "The mtcars data.")
```

You should also have a look at Table \@ref(tab:mtcars2).

```{r mtcars2, echo=FALSE}
knitr::kable(mtcars[1:5, 6:11], caption = "More columns from the mtcars data.")
```

You should also have a look at Table \@ref(tab:mtcars3).

```{r mtcars3, echo=FALSE}

flextable(mtcars[1:5 + 5,1:5]) %>%
  set_caption("More rows from the mtcars data.")

```

```{r mtcars4, echo=FALSE}

flextable(mtcars[1:5 + 5,1:5]) %>%
  set_caption("Yet another table from the mtcars data.")

```
